### PR TITLE
.NET Core 2.0.5

### PR DESCRIPTION
**Pull request by martincostello**
Update for [.NET Core 2.0.5](https://github.com/dotnet/core/blob/master/release-notes/download-archives/2.0.5-download.md).

### CODE REVIEW

**Comment by martincostello** [comment]
@jberezanski @riezebosch Would either of you to merge this and publish to chocolatey please?

**Comment by riezebosch** [comment]
fixed some left-behind version numbers (and amended the commit).

**Comment by martincostello** [comment]
Thanks! Sorry about the missed bits, all the various changes to do the version updates are a bit fiddly to do. It's a shame this process isn't more easily automatable.

**Comment by riezebosch** [comment]
Yeah, did an attempt to automate it but the information is too shattered.

**Comment by riezebosch** [comment]
PS: Since you are doing all the updates lately maybe we should make you (co-)maintainer?

**Comment by martincostello** [comment]
@riezebosch I'm happy to get involved if it makes the overall maintenance easier 😃

**Comment by riezebosch** [comment]
I got an [endpoint from the cli-team](https://github.com/dotnet/cli/issues/8386) with version information and download-url's! So expect AU working shortly! Already fixed it for the [dotnetcore-sdk](https://github.com/riezebosch/BoxstarterPackages/blob/master/dotnetcore-sdk/Update.ps1).

**Comment by martincostello** [comment]
Awesome - that makes things much simpler!

**Pull request merged**
