### PR TITLE
.NET Core 1.1.1

### LINKED ISSUE #7: .NET Core 1.1.1 package
Now the SDK has RTM'd, the runtime has been updated again to 1.1.1.

### PR DESCRIPTION
**Pull request by martincostello**
This PR _hopefully_ adds support for .NET Core 1.1.1 runtime and .NET Core 1.0.4 & 1.1.1 Windows Server Hosting to resolve #7.

Ideally it would also add the .NET Core 1.0.4 runtime as well (as it was released at the same time as the new LTS version, where as 1.1.1 is the latest Current version), but the structure of this repo only allows for one version of each package at a time.

### CODE REVIEW

**Comment by martincostello** [comment]
Hashes were generated using PowerShell's ```Get-FileHash``` cmdlet.

**Comment by martincostello** [comment]
Whoops. Those were the SDK paths...

**Comment by jberezanski** [comment]
Looks good! Please note that the meta packages `dotnetcore` and `dotnetcore-runtime` should be updated as well, to point to the newer runtime version in `<dependency>`.

**Comment by jberezanski** [comment]
Ah, you beat me to it :)

**Comment by martincostello** [comment]
I literally just found them 👍

**Comment by jberezanski** [comment]
One more change, please: the "using chocolatey-core.extension..." statement in package release notes was relevant only for the 1.1.0 release and should be removed now (the only change in this release is the update of version).

**Comment by martincostello** [comment]
No problem, I'll update that now.

**Comment by jberezanski** [comment]
I need to be running now, but I'll test this and hopefully publish in a few hours.

> Ideally it would also add the .NET Core 1.0.4 runtime as well (as it was released at the same time as the new LTS version, where as 1.1.1 is the latest Current version), but the structure of this repo only allows for one version of each package at a time.

I'm actively thinking about it and will probably do something about it in near future.

**Comment by martincostello** [comment]
Should be good to go now.

**Comment by jberezanski** [comment]
How about updating dotnetcore-runtime.portable as well?

**Comment by martincostello** [comment]
Missed that one - done now.

**Comment by jberezanski** [comment]
While testing, I've discovered that the runtime does not work on Win7 without KB2533623, so I've added the dependency.

**Comment by jberezanski** [comment]
I'll run the tests again later and merge it if nothing pops up.

**Comment by martincostello** [comment]
Cool, thanks 👍

**Comment by jberezanski** [comment]
Thanks a lot for your contribution!

**Pull request merged**
