### PR TITLE
.NET Core 2.0.3

### PR DESCRIPTION
**Pull request by martincostello**
Update for .NET Core 2.0.3.

Awaiting a working download link for the x86 portable runtime as the link [here](https://github.com/dotnet/core/blob/master/release-notes/download-archives/2.0.3.md) isn't working at the moment, so I can't compute the SHA-256 hash yet.

### CODE REVIEW

**Comment by riezebosch** [comment]
Here it is: https://dotnetcli.blob.core.windows.net/dotnet/checksums/2.0.3-runtime-sha.txt

**Comment by martincostello** [comment]
@riezebosch Is it OK to use SHA-512 in the manifest instead of SHA-256? I did find the checksum file, but was unsure if changing the hash format would be supported.

**Comment by riezebosch** [comment]
As far as I'm concerned that's perfectly fine. Chocolatey supports it for over 2 years already and I like it to use checksum the publisher provides. Previously the checksums where published as sha256.

**Comment by martincostello** [comment]
That's cool - I'll update the PR now, so we should be good as long as they fix the broken download link instead of changing it to something else.

**Comment by martincostello** [comment]
I've updated the hashes to SHA-512 and added the link as-given in the documentation (though it still doesn't work).

**Comment by martincostello** [comment]
@riezebosch Download link for the x86 portable SDK now fixed.

**Comment by martincostello** [comment]
Is this good to merge now so the updated package can be published to Chocolatey?

**Comment by martincostello** [comment]
Thanks 🎉

**Comment by martincostello** [comment]
Looks like a checksum is incorrect:

```ERROR: Checksum for 'C:\Windows\TEMP\chocolatey\dotnetcore-runtime.install\2.0.3\dotnet-runtime-2.0.3-win-x64.exe' did not meet 'efa901c610507249ed9b715e3f261f655550e68c0684eb04d09a4f55d3c6fa45f7f28d0810830411dc87611c99ae8a90daefcf488fd704d63404fcddb8f5c4ba' for checksum type 'sha512'. Consider passing the actual checksums through with --checksum --checksum64 once you validate the checksums are appropriate. A less secure option is to pass --ignore-checksums if necessary.```

**Pull request merged**
