### PR TITLE
Update to 1.1.0

### PR DESCRIPTION
**Pull request by zackschuster**
Updated all three nuspec files and the install package's links + checksums. Let me know if I missed anything.

### CODE REVIEW

**Comment by jberezanski** [comment]
Thanks!

I'll only adjust the package release notes a bit (my intention is for them to be scoped to each software version, i.e. each software version increase results in an "initial package" for that version). Other than that, looks good to go.

Oh, but next time, please avoid mixing reformatting with other changes in the same commit.

**Comment by zackschuster** [comment]
Sorry about that. I'll keep them in separate commits in the future. 
Speaking of which, I have some files prepped for the sdk packages, would you mind if I PR'd them? 






On Tue, Nov 29, 2016 at 1:49 PM -0800, "Jakub Berezanski" <notifications@github.com> wrote:












Merged #2.

**Comment by jberezanski** [comment]
The SDK packages in this repo are currently 0-byte stubs; we haven't finished porting them from @Riezebosch's repo yet. The plan was to: 1) rename the existing [dotnetcore-sdk](https://github.com/riezebosch/BoxstarterPackages/tree/master/dotnetcore-sdk) package to dotnetcore-sdk.install, 2) make dotnetcore-sdk a meta-package (similar to dotnetcore-runtime) and, finally, 3) add the dotnetcore-sdk.portable package. I've been meaning to do it for _months_ now, but never could find the time.

If you only mean to update the SDK to 1.1.0, I suggest you submit the PR [here](https://github.com/riezebosch/BoxstarterPackages/tree/master/dotnetcore-sdk). But, if you would like to help with the above plan, that would be great!

**Comment by jberezanski** [comment]
FYI, the reformatting broke markdown rendering of release notes - I had to revert it.

**Comment by zackschuster** [comment]
Can I fix the commit from this PR or should I open a new one?

**Comment by jberezanski** [comment]
I've already fixed it. The packages are now live on chocolatey.org, pending moderation.

Thanks for your PR, it gave me enough motivation to update other dotnetcore packages as well :)

**Comment by riezebosch** [comment]
@jberezanski Feel free to include the dotnetcore-sdk package in this repo. It just makes more sense.

**Pull request merged**
